### ISSUE TITLE
403 Errors Suddenly

### ISSUE THREAD

**Issue by JaraMohnson** [r-spacex/SpaceX-API#1209]
Hey guys - I'm writing up a project for a job interview and the calls had been working just fine. After a debug session, I suddenly got these 403 errors. 
System.Net.WebException: 'The remote server returned an error: (403) Forbidden.'

I'm running this out of Visual Studio in ASP.NET MVC app - not sure why it's kicking back at me now! 

Thanks in advance for any ideas on what I may be doing wrong here 
           
EDIT: looking at the status page I'm seeing a potential issue there - will check tomorrow if things have settled down!

**Comment by ok-ai** [comment]
yeah~ I just got the same errors...

In postman every request gives me the same response:

Checking if the site connection is secure
Enable JavaScript and cookies to continue
api.spacexdata.com needs to review the security of your connection before proceeding.

in my memory some days ago the request in postman will feed back the response in json format directly, but now due to the security check, my website can not parse and update the lasted data, so you know...I have to shutdown my website server for a while..

So my brother, how to solve this problem...

**Comment by jakewmeyer** [comment]
Still getting errors? Likely was from a Cloudflare captcha as a result of the DDOS

**Comment by iNoles** [comment]
I get HTTP Error 429 (too many requests)

**Comment by JaraMohnson** [comment]
Hi @jakewmeyer ! The Forbidden errors went away perfectly fine for me once I just waited for that bigger issue to settle down. :) 

Appreciate you getting back to us so quickly!

**Comment by JaraMohnson** [comment]
> I get HTTP Error 429 (too many requests)

@iNoles , I was getting this too. The API wasn't happy with me because I had an API call within a loop - lol. Once I fixed that I didn't have any issues!! 
If you keep getting the error, save yourself the frustration and just work on other parts of the code and let it cool down?

**Comment by jakewmeyer** [comment]
@iNoles @JaraMohnson Still getting 429? I upped the rate limit to 5000 requests/hour

**Comment by JaraMohnson** [comment]
Smooth over here!! thank you SO much!
